[workspace]
members = [
    "pkl-bind",
    "pkl-derive",
    "pkl-gen",
    "test_suite",
]
resolver = "2"

[patch.crates-io]
pkl-bind = { path = "pkl-bind" }

[workspace.dependencies]
proc-macro2 = { version = "1.0.74" }
quote = { version = "1.0.35" }
syn = { version = "2.0.46" }
